apiVersion: v2
name: authz
description: ArgoCD Apps used to deploy Authorization infrastructure
type: application
version: 0.2.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.23.0
