site_name: AuthZ
site_url: https://0.0.0.0/
repo_url: https://github.com/DiamondLightSource/authz
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - include-markdown
    - awesome-pages
    - mermaid2
themes:
    name: material
    features:
        - navigation.indexes
