image:
  repository: docker.io/openpolicyagent/opa
  pullPolicy: IfNotPresent
  tagOverride: ""
  version: ""
  envoy: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: info
orgData:
  enabled: true
  bundlerSecret:
    name: bundler
    key: bearer-token
orgPolicy:
  enabled: false
  userinfoEndpoint: https://auth.diamond.ac.uk/cas/oidc/oidcProfile
configOverride: {}
extraConfig: {}
extraServices: {}
extraBundles: {}
envOverride: []
extraEnv: []
portOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
