image:
  repository: docker.io/openpolicyagent/opa
  pullPolicy: IfNotPresent
  tag: 0.59.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

opa:
  configOverride: {}
  extraConfig: {}
  extraServices: {}
  extraBundles: {}
  envOverride: []
  extraEnv: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
