apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  config.yaml: |
    {{- if .Values.configOverride }}
    {{- .Values.configOverride | toYaml | nindent 4 }}
    {{- else }}
    services:
      diamond-bundler:
        url: https://authz.diamond.ac.uk
        credentials:
          bearer:
            token: ${BUNDLER_BEARER_TOKEN}
      ghcr:
        url: https://ghcr.io
        type: oci
      {{- if .Values.extraServices }}
      {{- .Values.extraServices | toYaml | nindent 6 }}
      {{- end }}
    {{- if or .Values.orgData.enabled .Values.orgPolicy.enabled .Values.extraBundles }}
    bundles:
      {{- if .Values.orgData.enabled }}
      diamond-permissionables:
        service: diamond-bundler
        resource: bundle.tar.gz
        polling:
          min_delay_seconds: 10
          max_delay_seconds: 60
      {{- end }}
      {{- if .Values.orgPolicy.enabled }}
      diamond-policies:
        service: ghcr
        resource: ghcr.io/diamondlightsource/authz-policy:0.0.16
        polling:
          min_delay_seconds: 30
          max_delay_seconds: 120
      {{- end }}
      {{- if .Values.extraBundles }}
      {{- .Values.extraBundles | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if .Values.extraConfig }}
    {{- .Values.extraConfig | toYaml | nindent 4 }}
    {{- end }}
    {{- end }}
