apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opa.service.type }}
  ports:
    - port: {{ .Values.opa.service.port }}
      targetPort: opa-http
      protocol: TCP
      name: http
  selector:
    {{- include "opa.selectorLabels" . | nindent 4 }}
