apiVersion: v1
kind: Service
metadata:
  name: {{ include "bundler.fullname" . }}
  labels:
    {{- include "bundler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bundler.service.type }}
  ports:
    - port: {{ .Values.bundler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bundler.selectorLabels" . | nindent 4 }}
