{{- if .Values.opal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opal-server.serviceAccountName" . }}
  labels:
    {{- include "opal-server.labels" . | nindent 4 }}
  {{- with .Values.opal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
