{{ if .Values.openfga.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "common.names.fullname" $ }}-openfga
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.arogproj.io
spec:
  project: {{ default .Release.Namespace .Values.project }}
  source:
    repoURL: https://openfga.github.io/helm-charts
    targetRevision: {{ .Values.openfga.targetRevision | quote }}
    chart: openfga
    {{- if .Values.openfga.valuesObject }}
    helm:
      valuesObject:
          {{ .Values.openfga.valuesObject | toYaml | nindent 10 }}
    {{- end }}
  destination:
    name: {{ .Values.destination.name }}
    server: {{ .Values.destination.server }}
    namespace: {{ default .Release.Namespace .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
