{{ if .Values.bundler.staticDataPattern -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-static-data
  namespace: {{ .Release.Namespace }}
data:
  {{ range $path, $_ := .Files.Glob .Values.bundler.staticDataPattern -}}
  {{ $data := $.Files.Get $path -}}
  {{ if  (trim $data) -}}
  {{ $path }}: |-
    {{- $data | nindent 4 }}
  {{ end -}}
  {{- end -}}
{{- end }}
