name: Bundler Lint

on:
  workflow_call:

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Check Dependencies with Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v2.0.5
        with:
          manifest-path: bundler/Cargo.toml
          command: check bans licenses sources

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Download Prepared Queries Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: prepared-queries
          path: bundler/.sqlx

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.7

      - name: Check Formatting
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: >
            --manifest-path bundler/Cargo.toml
            --all
            --check

      - name: Lint with Clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: >
            --manifest-path bundler/Cargo.toml
            --all-targets
            --all-features
            --no-deps
            --
            --deny warnings

