name: Bundler Docs

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Download Prepared Queries Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: prepared-queries
          path: bundler/.sqlx

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.7

      - name: Build docs
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: >
            --no-deps
            --all-features
            --document-private-items
            --manifest-path bundler/Cargo.toml

      - name: Fix file permissions for pages
        run: chmod -R +rX bundler/target/doc

      - name: Upload Bundler Docs Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: bundler-docs
          path: bundler/target/doc/bundler
