name: Bundler Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      ispyb:
        image: ghcr.io/diamondlightsource/ispyb-database:v3.0.0
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd "/usr/local/bin/healthcheck.sh --defaults-file=/ispyb/.my.cnf --connect"
          --health-interval 1s
          --health-retries 60
    env:
      DATABASE_URL: mysql://root:rootpassword@localhost/ispyb_build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.7

      - name: Check Formatting
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: >
            --manifest-path bundler/Cargo.toml
            --all
            --check

      - name: Lint with Clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: >
            --manifest-path bundler/Cargo.toml
            --all-targets
            --all-features
            --no-deps
            --
            --deny warnings

