name: Lint Commits

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v6.1.2
        with:
          configFile: .commitlintrc.json
          failOnWarnings: true
