name: Helm Charts Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        chart:
          - opa
          - bundler
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install chart dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update charts/${{ matrix.chart }}

      - name: Package Chart
        run: helm package charts/${{ matrix.chart }}

      - name: Generate Image Name
        run: echo IMAGE_REPOSITORY=oci://ghcr.io/$(echo "${{ github.repository }}-${{ matrix.chart }}" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: helm push $(ls ${{ matrix.chart }}-*.tgz) ${{ env.IMAGE_REPOSITORY }}
