name: Techdocs Publish

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get docs artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: user-docs
          path: site

      - name: Publish docs to s3 bucket
        if: github.ref == 'refs/heads/main'
        run: >
          timeout -v 10m
          npx @techdocs/cli publish
          --entity default/system/auth-bundler
          --publisher-type awsS3
          --storage-name techdocs
          --awsEndpoint https://s3.echo.stfc.ac.uk
          --awsS3ForcePathStyle
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
