name: Publish Docs

on:
  workflow_run:
    workflows:
      - User Docs
      - Bundler Docs
    types:
      - completed

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Download User Docs Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: user-docs
          path: docs

      - name: Download User Docs Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: bundler-docs
          path: docs/bundler

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: docs

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: combine
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      - name: Publish docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.2
