name: User Docs

on:
  push:
  pull_request:

jobs:
  build:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: pip install -r docs/requirements.txt

      - name: Build User Docs
        run: mkdocs build

      - name: Fix file permissions for pages
        run: chmod -R +rX site

      - name: Upload User Docs Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: user-docs
          path: site

  publish_s3:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get docs artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: user-docs
          path: site

      - name: Publish docs to s3 bucket
        if: github.ref == 'refs/heads/main'
        run: >
          timeout -v 10m
          npx @techdocs/cli publish
          --entity default/system/auth-bundler
          --publisher-type awsS3
          --storage-name techdocs
          --awsEndpoint https://s3.echo.stfc.ac.uk
          --awsS3ForcePathStyle
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TECHDOCS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TECHDOCS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ""
